spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb;MODE=MySQL;AUTO_SERVER=TRUE
    username: user
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true